In [62]:
# importamos las librerías que necesitamos
from sklearn.datasets import load_iris # datos de iris
from sklearn.tree import DecisionTreeClassifier # árbol de decisión para clasificación
from sklearn.tree import export_graphviz
import graphviz
import matplotlib.pyplot as plt
import numpy as np

In [48]:
iris = load_iris()

In [49]:
# para la variable a predecir también hacemos lo mismo
print(iris.target[47:53])

[0 0 0 1 1 1]


In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(iris.data,iris.target)

In [65]:
# vamos a usar un árbol de profundidad 2
arbol = DecisionTreeClassifier(max_depth=2) 
arbol.fit(X_train, y_train) # entrenamiento del árbol

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=2, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')

In [66]:
print(arbol.score(X_test,y_test))

0.9473684210526315


In [67]:
# podemos usar el método predict para obtener predicciones
print( arbol.predict(iris.data[47:53]) )

[0 0 0 1 1 1]


In [68]:
# si queremos saber las probabilidades podemos usar el método predict_proba
print( arbol.predict_proba(iris.data[47:53]) )

[[1.    0.    0.   ]
 [1.    0.    0.   ]
 [1.    0.    0.   ]
 [0.    0.925 0.075]
 [0.    0.925 0.075]
 [0.    0.925 0.075]]


In [73]:
from sklearn.tree import DecisionTreeRegressor
tree = DecisionTreeRegressor(max_depth=2) 
tree.fit(X_train, y_train) 

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=2,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=None, splitter='best')

In [74]:
print(tree.score(X_test,y_test))

0.931241169544741


In [75]:
print( tree.predict(iris.data[47:53]) )

[0.    0.    0.    1.075 1.075 1.075]
